# Generated by Django 4.0 on 2022-01-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offroad_park',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
